# Generated by Django 5.0.6 on 2024-05-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_metrics',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
